docs/consuming-any-data.adoc, docs/dynamic-property-configuration.adoc, docs/getting-started.adoc, docs/key-blocking.adoc, docs/monitoring.adoc, docs/rate-limiting.adoc, docs/retry-queueing.adoc, docs/task-compaction.adoc, docs/why-decaton.adoc, processor/src/main/java/com/linecorp/decaton/processor/SubscriptionStateListener.java, processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java, processor/src/main/java/com/linecorp/decaton/processor/runtime/SubscriptionBuilder.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java
- Add the capability to observe subscription state change, which is useful for integration testing
=> Add the capability to observe subscription internal state

processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorUnitTest.java
Fixes this fail: https://travis-ci.com/github/line/decaton/jobs/303572037
=> Fix flaky failing ProcessorUnitTest

processor/src/it/java/com/linecorp/decaton/processor/MetricsTest.java
Fixup for flaky integration test added by #40
=> Fix flaky testDetectStuckPartitions to be stable

benchmark/src/main/java/com/linecorp/decaton/benchmark/AsyncProfilerProfiling.java, cb/cb.sh
=> Fixups for cb

README.md, cb/run-bm.sh
Also added a link for perf dashboard from README.
=> Adjust CB condition to have longer observation for accurate result

developer-docs/making-release.md
=> Fix typo in making-release.md

benchmark/src/main/java/com/linecorp/decaton/benchmark/DecatonRunner.java
by #60 , an invocation of `KafkaConsumer#position` has been deleted from `ConsumerRebalanceListener#onPartitionsAssigned`. This seems to have caused a tiny behavior change, in particular, the initial offset reset now happens in later timing than before, which was occurring at calling `position()` in previous implementation.
This led our benchmark to break by timing out awaiting all produced records to have completed, because in the current implementation, the offset hasn't yet reset to 0 when the benchmark program starts producing tasks, causing a consumer in `ProcessorSubscription` to reset the offset to some value larger than 0 because there's already some records present in the topic, and the offset reset policy is `latest` (default).
Thanks a lot for @ocadaruma for investigating this!
=> Use auto.offset.reset=earliest for benchmark

VERSIONING.md
=> Update VERSIONING doc following the recent public API separation

build.gradle, testing/build.gradle
JUnit : 4.12 -> 4.13
Hamcrest : 1.3 -> 2.2 (changed artifact name)
Mockito : 2.23 -> 3.7
=> Upgrade test dependencies

processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java
=> Properly shutdown subscription even when its closed without started

spring/build.gradle
spring-boot-starter : 2.1.7 -> 2.5.6
=> Upgrade Spring Boot version to 2.5.6(#127)

build.gradle
=> shadeAllDependencies needs to be evaluated after subproject configuation

cb/run-bm.sh
=> Fixup; using out_dir as tmp filename doesn't work

.github/workflows/ci.yml, build.gradle, processor/build.gradle, processor/src/jmh/java/com/linecorp/decaton/processor/runtime/OutOfOrderCommitControlBenchmark.java, processor/src/test/resources/logback.xml
=> Fix broken microbenchmark of processor module

benchmark/build.gradle, build.gradle, centraldogma/build.gradle, processor/build.gradle, testing/build.gradle
=> Downgrade SLF4J / logback for compatibility

benchmark/build.gradle, brave/build.gradle, build.gradle, centraldogma/build.gradle, centraldogma/src/main/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplier.java, client/src/main/java/com/linecorp/decaton/client/DecatonClient.java, client/src/test/java/com/linecorp/decaton/client/kafka/PrintableAsciiStringSerializerTest.java, processor/build.gradle, processor/src/it/java/com/linecorp/decaton/processor/CoreFunctionalityTest.java, processor/src/it/java/com/linecorp/decaton/processor/metrics/MetricsTest.java, processor/src/jmh/java/com/linecorp/decaton/processor/runtime/OutOfOrderCommitControlBenchmark.java, processor/src/main/java/com/linecorp/decaton/processor/runtime/DefaultSubPartitioner.java, processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ThreadScope.java, processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/Utils.java, processor/src/test/java/com/linecorp/decaton/processor/TaskMetadataTest.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/DynamicPropertyTest.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/SubPartitionerTest.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/AbstractDecatonPropertiesTest.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ConsumeManagerTest.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/DecatonProcessorSupplierImplTest.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/DecatonTaskRetryQueueingProcessorTest.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/PartitionContextsTest.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessingContextImplTest.java, processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/RateLimiterTest.java, spring/build.gradle, testing/build.gradle, testing/src/main/java/com/linecorp/decaton/testing/processor/ProducerAdaptor.java
- centraldogma : 0.57.0 -> 0.61.0
- spring-boot : 2.5.x -> 2.7.11
- Jackson : 2.13.x -> 2.14.2
- micrometer : 1.7.x -> 1.10.6
- brave 5.13.x -> 5.15.1
And fix a few of the common warnings
=> Bump dependencies

processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PerKeyQuotaManager.java
- My bad, I made a stupid mistake in #192
=> Pass Count-Min parameters correctly

benchmark/debm.sh, benchmark/src/main/java/com/linecorp/decaton/benchmark/AsyncProfilerProfiling.java, benchmark/src/main/java/com/linecorp/decaton/benchmark/DecatonRunner.java, benchmark/src/main/java/com/linecorp/decaton/benchmark/Recording.java, benchmark/src/main/resources/logback.xml
* Upgrade async-profiler version (to support future JVM versions) 
* Metrics accessibility for benchmark execution
* Get rid of thread local for recordings
=> Some updates and improvements for the benchmark module

processor/src/main/java/com/linecorp/decaton/processor/metrics/Metrics.java
=> New metrics follow up for #218 

commit-data/a3f14197b71c65a7aa8d83b78d5c9756dbf9ca89/tasks_1000k_latency_0ms_concurrency_20-benchmark.json, commit-data/a3f14197b71c65a7aa8d83b78d5c9756dbf9ca89/tasks_100k_latency_10ms_concurrency_20-benchmark.json
Follow-up for https://github.com/line/decaton/pull/228
=> Fix invalid json caused by async-profiler update

index.html
Merge after https://github.com/line/decaton/pull/231
=> Add graphs of vthread mode
