line/decaton

docs/consuming-any-data.adoc
docs/dynamic-property-configuration.adoc
docs/getting-started.adoc
docs/key-blocking.adoc
docs/monitoring.adoc
docs/rate-limiting.adoc
docs/retry-queueing.adoc
docs/src/main/java/com/linecorp/decaton/DocumentChecker.java
docs/task-compaction.adoc
docs/why-decaton.adoc
processor/src/main/java/com/linecorp/decaton/processor/runtime/OutOfOrderCommitControl.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/PartitionContexts.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/OutOfOrderCommitControlTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/PartitionContextTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/PartitionContextsTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/SubPartitionerTest.java

fixed #16 
By deprecating use of `KafkaConsumer#committed`, the issue is likely fixed but I guarded `offsetCommit` aginst `TimeoutException` as well to avoid future repeat of the same situation.
3rd commit contains completely unrelated change that I found when looking at some code.

 Deprecate use of KafkaConsumer#committed by locally cached committed offset

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/LoggingContext.java

Despite the slf4j's document states null value is allowed, it also says that it depends on underlying implementation.
In fact I found that log4j, one of major implementation doesn't supports it (logback does).
It should be better to avoid passing null values in any cases without expectation for the logger to be used.

Fix LoggingContext to not put null value into MDC

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/SubscriptionBuilder.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/SubscriptionBuilderTest.java

Resolves #29 
`org.apache.kafka.clients.producer.ProducerConfig.configNames()` returns the set of producer properties names.  
Suppress warnings because of unused properties by taking an intersection of `consumerConfig` and it.

Filter consumerConfig to use it as a producerConfig 

---

processor/src/it/java/com/linecorp/decaton/processor/RateLimiterTest.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/AveragingRateLimiter.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ExecutionScheduler.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/InfiniteBlocker.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/PartitionProcessor.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessPipeline.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorUnit.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/RateLimiter.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/TaskRequest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ExecutionSchedulerTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/PartitionProcessorTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessPipelineTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorUnitTest.java
testing/src/main/java/com/linecorp/decaton/testing/TestUtils.java
testing/src/main/resources/log4j.properties

This patch changes responsibility of `ProcessorUnit` and `ProcessPipeline`.
As-is:
* `ProcessorUnit` => manage per-thread queue, manage offset completes(especially, when processor returns w/o deferring completion) and some duration/error metrics 
* `ProcessPipeline` => task extraction, execution scheduling and some duration/error measurements
To-be:
* `ProcessorUnit` will focus on manage per-thread queue
* `ProcessPipeline` takes all the others and property distinguish failures at task extraction, scheduling and processing
All locations that pauses/sleeps upon task to become ready for processing are now checking termination flag so that once the termination starts they stops and returns immediately.
Now exceptions from user-supplied `DecatonProcessor` and unexpected exceptions from …

Isolate exceptions threw from decaton's internal with those from user-supplied code

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/AveragingRateLimiter.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/DynamicRateLimiter.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/InfiniteBlocker.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/RateLimiter.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/DynamicRateLimiterTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/RateLimiterTest.java

Follow-up for #32 
* Make `DynamicRateLimiter` to conservatively check if limiter has returned because of termination or switch
* Revert limiters to return even partially awaited time to record metrics correctly especially when it resumed from PAUSE state

 Fix DynamicRateLimiter to conservatively check and retry on unexpected limiter return

---

benchmark/README.md
benchmark/build.gradle
benchmark/debm.sh
benchmark/src/main/java/com/linecorp/decaton/benchmark/AsyncProfilerProfiling.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/Benchmark.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/BenchmarkConfig.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/BenchmarkResult.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/Execution.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/ForkingExecution.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/InProcessExecution.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/JvmTracker.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/Main.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/Profiling.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/Recording.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/RecordsGenerator.java
benchmark/src/main/resources/logback.xml
processor/src/it/java/com/linecorp/decaton/processor/PerformanceBoundTest.java
processor/src/main/java/com/linecorp/decaton/processor/metrics/Metrics.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java

The benchmark module is useful not only for tracking performance regression between decaton versions but also for persuading even further performance optimizations and/or to figure out why the performance regression has happened.
To get more insights from benchmark we need more information from it most significantly profiling.
Of course we can run profilers like async-profiler externally with synchronizing timing with benchmark execution, but it's highly useful to integrate the profiling into benchmark itself so that:
* We can easily perform profiling just by single extra command line switch
* Benchmark code knows more about when it should start profiling. e.g, should not profile until warmup completes.
* Made benchmark runner to fork a separate JVM to run consumer instance. This has …

Add profiling capability to benchmark

---

build.gradle
processor/src/it/java/com/linecorp/decaton/processor/MetricsCleanupTest.java
processor/src/main/java/com/linecorp/decaton/processor/metrics/Metrics.java
processor/src/main/java/com/linecorp/decaton/processor/metrics/ValueGauge.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/DecatonTaskRetryQueueingProcessor.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ExecutionScheduler.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessPipeline.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorUnit.java
processor/src/test/java/com/linecorp/decaton/processor/metrics/MetricsTest.java

Currently once Decaton's internal metrics is created it never gets cleaned up. 
This is causing some metrics to leftover in scrape resulting making it very confusing to distinguish the value already became invalid by partition reassignment vs the currently active and value.
This PR ensures all metrics to cleanup at their corresponding scope's destruction time.
Also the micrometer dependency is upgraded to make the meter removal function work properly.

Cleanup all metrics at corresponding shutdown

---

processor/src/main/java/com/linecorp/decaton/processor/ProcessingContext.java

According to this documentation: https://github.com/line/decaton/blob/master/docs/retry-queueing.adoc#retry-with-asynchronous-processing and implementation deferred completion will be complete when `retry()` is called. 
The current comment is confusing as it says 
```
caller *MUST* call {@link DeferredCompletion#complete()} method in any cases.
```
which is not true with the current implementation.

Improve comment for deferred completion when using retry

---

docs/monitoring.adoc

Follow-up document regarding breaking change for metric decaton.partitions.paused

---

benchmark/Dockerfile
benchmark/debm.sh
benchmark/run-bm-docker.sh
benchmark/src/main/java/com/linecorp/decaton/benchmark/AsyncProfilerProfiling.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/BenchmarkConfig.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/BenchmarkResult.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/InProcessExecution.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/JvmUtils.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/Main.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/Taskstats.java

When I was investigating decaton's performance degaradation suspect regarding kafka-client upgrade (which was not the case though), I found that in addition to the profiling it's very helpful to have per-java thread activity information particularly, declay accounting of each tasks to distinguish whether the certain processing latency is due to wait such as I/O.
At that time I just used linux-dist supplied "getdelays.c" program with manual thread-task mapping but I made it much sophisticated and usable for jvm threads by https://github.com/kawamuray/jtaskstats and now attempting to integrate it into decaton's benchmark module.
This PR adds `--taskstats` and `--taskstats-bin` option to benchmark module to enable taskstats recording for the threads of JVM at the end of benchmark execution. …

Add taskstats support for benchmark module to get insight about each thread's behavior

---

build.gradle
processor/build.gradle
processor/src/it/java/com/linecorp/decaton/processor/CoreFunctionalityTest.java
processor/src/it/java/com/linecorp/decaton/processor/MetricsTest.java
processor/src/it/java/com/linecorp/decaton/processor/RetryQueueingTest.java
testing/build.gradle
testing/src/main/java/com/linecorp/decaton/testing/KafkaAdmin.java
testing/src/main/java/com/linecorp/decaton/testing/RandomRule.java
testing/src/main/java/com/linecorp/decaton/testing/TestUtils.java
testing/src/main/java/com/linecorp/decaton/testing/processor/AtLeastOnceDelivery.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessOrdering.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessedRecord.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessingGuarantee.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessorTestSuite.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProducedRecord.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ReprocessAwareOrdering.java
testing/src/main/java/com/linecorp/decaton/testing/processor/SerialProcessing.java
testing/src/main/java/com/linecorp/decaton/testing/processor/TestTask.java

- This PR adds integration tests to check processing guarantees which are expected Decaton to always satisfy
- By this tests, we can make sure that future code changes don't break processing semantics of Decaton
- [ProcessingGuarantee.java](https://github.com/line/decaton/pull/35/files#diff-76bb76bb3bdb59bf6dca0f19c07e0a04R33) contains the interface for guarantee and enums of available guarantees.
- [ProcessorTestSuite](https://github.com/line/decaton/pull/35/files#diff-75717a8b58a436b83a3fcecd1d91733dR57) is the class that performs integration test
- For how to use `ProcessorTestSuite`, please see [CoreFunctionalityTest](https://github.com/line/decaton/pull/35/files#diff-e7d47fe3e6d50565c8109a715d581436R31)

Add integration tests to check core functionality

---

benchmark/debm.sh
benchmark/src/main/java/com/linecorp/decaton/benchmark/BenchmarkConfig.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/BenchmarkResult.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/InProcessExecution.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/JsonResultFormat.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/Main.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/ResultFormat.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/Taskstats.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/TextResultFormat.java
cb/cb.sh
cb/config.template
cb/run-bm.sh
cb/sysinfo.sh

This PR attempts to address #45 .
As I reverted the previous `PerformanceBoundTest` in https://github.com/line/decaton/pull/44, the way to run benchmark in CI showed a stability issue in terms of benchmark results.
It might be an option to pursue another CI service that provides stabler environment, but I think it's much better to take full control of benchmark environment that provides predictable resource and stable results.
To do that, I propose a new manual way of executing benchmark in our own servers along with the way to visualize trend of results that was also missing in our first attempt.
1. A commit pushed
2. A scheduled job in our own machine continuously polls for new commits
3. Once detected, job executes benchmark and store the result into a dedicated directory …

Add manual git-based continuous benchmark

---

cb/cb.sh

* Let cb to continue to the next revision as I notice that some intermediate commits that doesn't build can easily make cb job to fail
* Fixes dumb mistake in wording

Let cb script to continue even if there is a failure

---

processor/src/it/java/com/linecorp/decaton/processor/CoreFunctionalityTest.java
processor/src/it/java/com/linecorp/decaton/processor/MetricsTest.java
processor/src/it/java/com/linecorp/decaton/processor/RateLimiterTest.java
processor/src/it/java/com/linecorp/decaton/processor/SubscriptionStateTest.java
processor/src/main/java/com/linecorp/decaton/processor/SubscriptionStateListener.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java
testing/src/main/java/com/linecorp/decaton/testing/TestUtils.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessorTestSuite.java

- Update H/W before shutting down to reduce process duplication
- By this fix, as long as we set partition.concurrency to 1 as like vanilla consumer, we can expect process duplication not to occur.
* Added a test about that

Update HW in shutdown procedure to reduce duplication fixes #23

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/Utils.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java

Decaton has been using `commitSync()` in pool-loop but there was some cases where it becomes a bottleneck especially when consumer's consuming in batch style where processing itself doesn't take much long due to latency awaiting OffsetCommit response from broker.
I think there's no point to wait offset commit's result synchronously in poll-loop except at 1. shutdown and 2. before rebalance.
This PR attempts to leverage async commit when decaton instance is consuming in regular loop so it won't be affected by high OffsetCommit latency from broker anymore.
There should be no essential difference with current way in terms of failure handling since we're anyway crushing exception from `commitSync()` now.

Commits offsets within consume-loop asynchronously to avoid blocking loop

---

docs/consuming-any-data.adoc
docs/dynamic-property-configuration.adoc
docs/getting-started.adoc
docs/key-blocking.adoc
docs/monitoring.adoc
docs/rate-limiting.adoc
docs/retry-queueing.adoc
docs/task-compaction.adoc
docs/why-decaton.adoc
processor/src/main/java/com/linecorp/decaton/processor/metrics/Metrics.java

Fixes #58 
- Clear `meters` on `close()`
- Since `meters` is now mutable, synchronize `close()` and `meter()`
- Make `meterRefCounts` non-synchronized to avoid double locking
- Add nullcheck for counters in `meterRefCounts`

Prevent NPE when closing Metrics twice

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java

Fixes #62 
`ProcessorSubscription` is a `Thread` hence it's `Runnable` as well, means it might be executed in a thread different from `ProcessorSubscription` itself.
The point of the assertion is to make sure the thread calling async commit's callback is the same as the thread called `commitAsync` so we should be able to relax the check to expect this case.
/cc @mauhiz

Fix calling thread assertion to be applicable for usage treating ProcessorSubscription as Runnable

---

build.gradle

- As #66 describes, shadowJar task includes class-path header which lists `shadow` dependencies in MANIFEST.MF
- Checking johnrengelman/shadow#324, it seems like built-in `shadow` configuration is "reserved" for the purpose to exclude dependency from resulting executable jar, which indeed needs manifest's class-path attributes
- This PR tries not to include class-path in manifest by stopping to use `shadow` configuration

Exclude class-path header from manifest fixes #66

---

benchmark/README.md
benchmark/build.gradle
benchmark/src/main/java/com/linecorp/decaton/benchmark/BenchmarkRmi.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/ForkingExecution.java
benchmark/src/main/java/com/linecorp/decaton/benchmark/Runner.java
build.gradle

- `benchmark` module is designed to be able to run arbitrary `Runner` implementation, not only built-in `DecatonRunner`
- But currently, running custom Runner implementation cannot be done without modifying decaton repository itself since `benchmark` module is not published
- This PR publishes `benchmark` module locally to be able to depend on it from custom runner
- not to maven central. to avoid a lot of redistributions
- change interprocess communication to RMI
- currently, interprocess communication is done through stdout
* but this forces custom runner not to output any information to stdout (and it isn't documented anywhere)
* we shouldn't restrict use of stdout since we usually output debug information to stdout

Publish benchmark module locally to add capability to implement custom runner

---

processor/src/it/java/com/linecorp/decaton/processor/RetryQueueingTest.java
processor/src/it/java/com/linecorp/decaton/processor/metrics/MetricsTest.java
processor/src/main/java/com/linecorp/decaton/processor/metrics/Metrics.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/CompactionProcessor.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/CompactionProcessorTest.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessorTestSuite.java

Attempt to fix #56 
* `testRetryQueuing` => not very sure but suspecting CI server's resource simply lacks to complete the workload
* `testMetricsCleanup` => likely involved by the above test's failure. timed out test likely gets terminated w/o completing finally block and it'll laves garbage in metrics registry on shared JVM.
* `testRaceConditionOnFlush` => no idea yet. occurrence is too rare and not a subject of this PR.

Fix flaky tests

---

client/src/main/java/com/linecorp/decaton/client/DecatonClient.java
client/src/main/java/com/linecorp/decaton/client/DecatonClientImpl.java
client/src/test/java/com/linecorp/decaton/client/DecatonClientImplTest.java
client/src/test/java/com/linecorp/decaton/client/DecatonClientTest.java

Hello, decaton team.
We are using decaton in our application and for one topic, we’d like to use the delayed event feature of decaton.  We are using decatonClient to publish events and there is no put method which can be used to custom  scheduledTime  and it’s hard to extend the DecatonClientImpl class. So I added the put method with delay duration (by duration or milliseconds) as parameter. 
Please take a look at it.

Add interface to decatonClient for customizing delay

---

docs/consuming-any-data.adoc
docs/dynamic-property-configuration.adoc
docs/getting-started.adoc
docs/key-blocking.adoc
docs/monitoring.adoc
docs/rate-limiting.adoc
docs/retry-queueing.adoc
docs/task-compaction.adoc
docs/tracing.adoc
docs/why-decaton.adoc
processor/src/main/java/com/linecorp/decaton/processor/ProcessingContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessingContextImpl.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/TaskRequest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/CompactionProcessorTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessPipelineTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessingContextImplTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorUnitTest.java

- Currently there's no way to refer Kafka's RecordHeader from DecatonProcessor
- Sometimes it's necessary to access metadata in the headers and propagate it from DecatonProcessor
* e.g. Spring-Kafka's request/reply semantics uses KafkaHeader to control message routing
- This PR makes DecatonProcessor to access Headers through `ProcessingContext`

Make record header accessible from DecatonProcessor fixes #73

---

docs/consuming-any-data.adoc
protocol/build.gradle

- Decaton doesn't compile on arm64 mac
* because protoc binary hasn't been published yet
```
% ./gradlew :processor:check
> Task :common:compileJava UP-TO-DATE
> Task :common:processResources NO-SOURCE
> Task :common:classes UP-TO-DATE
> Task :common:jar UP-TO-DATE
> Task :protocol:extractIncludeProto UP-TO-DATE
> Task :protocol:extractProto UP-TO-DATE
> Task :protocol:generateProto FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':protocol:generateProto'.
> Could not resolve all files for configuration ':protocol:protobufToolsLocator_protoc'.
> Could not find protoc-osx-aarch_64.exe (com.google.protobuf:protoc:3.3.0).
Searched in the following locations:
https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.3.0/protoc-3.3.0-osx-aarc …
```

Add a workaround to build on arm64 mac

---

processor/src/main/java/com/linecorp/decaton/processor/DeferredCompletion.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/AssignmentManager.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/CommitManager.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ConsumeManager.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/OffsetRegressionException.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/OutOfOrderCommitControl.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/PartitionContexts.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/TaskConsumer.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/AssignmentManagerTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/CommitManagerTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ConsumeManagerTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/PartitionContextsTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java

As we talked in #53 , `ProcessorSubscription`'s getting bigger and complex by many functions being added to it.
I've attempted to refactor it by mainly extracting things into a separate classes.
The work is still in progress and I'm still considering what would be the best design (especially for TaskConsumer).
Please give early feedback if any!
Some notable changes that might impacts decaton's behavior:
* Stopped checking "offset regression" in rebalance listener and replaced it with `OffsetRegressionException` + on-demand repair.
* `contexts.maybeHandlePropertyReload()` now happens after updateHighWatermark, pause, resume

ProcessorSubscription refactoring

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorUnit.java

We found this cryptic error in our project (".. Offset of this will left uncommitted") but could not tell the cause since there is no stacktrace and no other log.
In this PR, I separate exception handling into
- InterruptedException : more or less expectable on shutdown; log at warn level
- the rest : really unexpected since `ProcessPipeline` also does its share of error handling

Log error trace when scheduleThenProcess fails

---

developer-docs/making-release.md
scripts/publish.sh

As we're going to manage versions following semver we're gonna need to specify the release version by ourselves.
Also deprecating stuff related to SNAPSHOT versions as we very rarely make a publish with a SNAPSHOT version.

Update release script to follow the new versioning scheme

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java

Fix a bug introduced by #60 .
Handling of `OffsetRegressionException` calls `assignManager.repair` which internally replaces the `PartitionContext` corresponding to the topic-partition, but it later still uses an old, previously grabbed `Context` causing subsequent `registerOffset` to never succeeds.

Fix regression handling

---

docs/src/main/java/com/linecorp/decaton/DocumentChecker.java

Background:
* We have started semantic versioning
* DocChecker always makes a release build to fail because most of the docs depends on `processor` module which gets updated almost 100% on each release.
Let's change DocChecker to fail only if `:base_version:` has lower major version than the version being released. 
This should be okay because:
* The objective of DocChecker is to avoid a document being outdated by forgotten to be updated
* A document gets outdated mainly by Public API changes. Otherwise, the content in doc is almost guaranteed to keep working.

DocChecker: Fail validation only if base_version differs to the release version by major version

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ConsumeManager.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ConsumeManagerTest.java

In current implementation the `consumer.pause()` may throw `IllegalStateException: No current assignment for partition ...`. 
When rebalance occurs, we save the list of partitions and restore the pause state later. However, since the rebalance might have taken over some partitions off from this instance, we have to filter these partitions from the argument of consumer.pause().
So this happens when all the following 3 conditions are met:
* There’s a paused partition
* Trigger rebalance (instance failure, restart)
* Rebalance taken over a partition from the current instance

Bugfix: Exception from consumer.pause() in rebalance due to passing already revoked partition

---

processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java

I was trying to address flaky test caused https://github.com/line/decaton/actions/runs/573915623 to fail, but while I'm working I realized that the current test implementation isn't reflecting my intention correctly.
The renewed version of test intends to check that a ProcessorSubscription continue working even after an offset regression.

Fix flaky and broken offsetRegression test

---

brave/build.gradle
brave/src/it/java/com/linecorp/decaton/processor/runtime/BraveTracingTest.java
processor/src/it/java/com/linecorp/decaton/processor/TracingTest.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessorTestSuite.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProducedRecord.java
testing/src/main/java/com/linecorp/decaton/testing/processor/TestTracingProducer.java

We already have an integration test for tracing in general, but it's good to confirm that the specific integration with Brave also works

Add integration tests for BraveTracingProvider

---

processor/src/test/java/com/linecorp/decaton/processor/metrics/MetricsTest.java

- Currently, `MetricsTest.testMetricsLifecycleManagement` fails if `CompactionProcessorTest` is executed first (depending on test execution order), because metrics for `CompactionProcessor` isn't cleaned up in any place
* https://github.com/line/decaton/blob/master/processor/src/main/java/com/linecorp/decaton/processor/processors/CompactionProcessor.java#L58
- One possible fix might be creating enclosing class for `CompactionProcessor` metrics and extends AbstractMetrics and close it upon processor close
- But rather, I fixed by clearing metrics in `@Before` to make testMetricsLifecycleManagement stable even we forget closing metrics in other classes

MetricsTest should clear metrics in advance to make test result stable fixes #94

---

client/src/main/java/com/linecorp/decaton/client/internal/DecatonTaskProducer.java
client/src/test/java/com/linecorp/decaton/client/internal/DecatonClientImplTest.java
processor/src/it/java/com/linecorp/decaton/processor/RetryQueueingTest.java
testing/src/main/java/com/linecorp/decaton/testing/EmbeddedKafkaCluster.java
testing/src/main/java/com/linecorp/decaton/testing/KafkaClusterRule.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessorTestSuite.java

- As described in #101, when we don't set `TaskMetadata#timestampMillis` explicitly on `TaskExtractor`, retry record's timestamp could be set to 0, which cause records to be deleted on broker side by retention immediately
- As retention-based log deletion takes record's timestamp into account, we should supply it independently of task's metadata timestamp (i.e. which is expected to be not related to Kafka's internal)
- Stop setting record's timestamp from task metadata in DecatonTaskProducer.
* We leave record's timestamp as null, so that KafkaProducer fills `System.currentTimeMillis`
* NOTE: This could be considered as "backward-incompatible change", so we should bump major version when releasing this fix
- Add an integration test to reproduce the phenomenon (i.e. retry tasks are …

Stop setting record timestamp from meta fixes #101

---

processor/src/main/java/com/linecorp/decaton/processor/LoggingContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorProperties.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ProcessPipeline.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ProcessingContextImpl.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/TaskRequest.java
processor/src/test/java/com/linecorp/decaton/processor/processors/CompactionProcessorTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessingContextImplTest.java

I found some code in decaton core causes massive object allocations (in proportional to consumed records) that causes high GC pressure.
The most significant ones are String allocation in `LoggingContext` (`TaskMetadata.toString()`) but `TaskRequest#id` too. (which is used only if trace level logging is enabled)
In this PR I saved those expensive object allocations by making it lazy or by adding a new flag to opt-out `LoggingContext` when its not necessary. 
* Adds new config `decaton.logging.mdc.enabled`

Reduce some object allocations that are identified as expensive by allocation profiling

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/SubscriptionBuilder.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ConsumerSupplier.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionScope.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/SubscriptionScope.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/DecatonTaskRetryQueueingProcessorTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ExecutionSchedulerTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/PartitionContextTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/PartitionContextsTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/PartitionProcessorTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessPipelineTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessorUnitTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessorsTest.java

In recent performance tuning experience, I found that the current default max.poll.records cap could be an issue.
As Decaton expects I/O intensive workload, which typically takes long to process a task, often the cost of work in Consumer#poll is negligible so we added hard limit for max.poll.records to size OOOCC easily.
However, in processor that does large batching of tasks, the processing time of a task could be few microseconds and in case `Consumer#poll` becomes an bottleneck. For such case, increasing max.poll.records contributes to better performance by eliminating some works repeated on every call of `Consumer#poll.`
This PR makes it to regard user-supplied max.poll.records in consumer config and discard hard limit, by using user-supplied max.poll.records to compute the size of …

Make max.poll.records customizable through consumer properties

---

build.gradle

**Motivation:** Micrometer 1.7 is out and we shouldn't stay 2 minor versions behind
I refrained from jumping right to 1.7 because
- it's still quite recent
- it introduces a breaking change by requiring prometheus simpleclient 0.10.0, which has a small change in metrics name convention. https://github.com/prometheus/client_java/releases/tag/parent-0.10.0

Upgrade micrometer to 1.6.6

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/SubscriptionBuilder.java

- Retry producer will be instantiated with `linger.ms = 0` unless we explicitly set, since it's kafka-clients's default.
- But typically it doesn't make much sense because we don't need such super short delivery latency for retry producer.

default linger.ms 0 doesn't make sense typically

---

docs/example/src/main/java/example/CentralDogmaSupplierMain.java
docs/example/src/main/java/example/IgnoreKeysMain.java
docs/example/src/main/java/example/JSONUserEventExtractor.java
docs/example/src/main/java/example/ProcessingRateMain.java
docs/example/src/main/java/example/ProcessorMain.java
docs/example/src/main/java/example/ProcessorMain2.java
docs/example/src/main/java/example/RetryQueuingMain.java
docs/example/src/main/java/example/TaskCompactionMain.java
docs/example/src/main/java/example/UserEventProcessorMain.java

Should have been done at 2.0 release.

Correct outdated import paths in docs/example project

---

centraldogma/src/main/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplier.java
centraldogma/src/test/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplierIntegrationTest.java
centraldogma/src/test/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplierTest.java

Fixes the following issues
```
java.lang.NullPointerException: null
at com.linecorp.decaton.centraldogma.CentralDogmaPropertySupplier.getProperty(CentralDogmaPropertySupplier.java:133)
at com.linecorp.decaton.processor.runtime.internal.AbstractDecatonProperties$Builder.setBySupplier(AbstractDecatonProperties.java:55)
at com.linecorp.decaton.processor.runtime.SubscriptionBuilder.properties(SubscriptionBuilder.java:103)
```
It happens because CD watchers don't notify synchronously and instead add a task to `watchScheduler`. So awaiting initial value does not guarantee that all watchers have been run. 
Each watcher polls CD, so with many processors / dynamic properties that's a lot of unnecessary load.
Note that child watchers do not react when a part of the file they are not watching is …

Use a single CentralDogma watcher per file

---

benchmark/src/main/java/com/linecorp/decaton/benchmark/BenchmarkConfig.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/RetryConfig.java

Small change to make it easer to reuse configs while changing some properties. (Specifically, this is useful for the case where we want to populate a `RetryConfig` automatically from Spring properties, but then set some fields programmatically)

Use toBuilder = true on config classes

---

processor/src/it/java/com/linecorp/decaton/processor/CoreFunctionalityTest.java
processor/src/it/java/com/linecorp/decaton/processor/RetryQueueingTest.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessorTestSuite.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProducerAdaptor.java
testing/src/main/java/com/linecorp/decaton/testing/processor/TestTracingProducer.java

- In https://github.com/line/decaton/pull/99, we made some spec change about `ProcessingContext#deferCompletion()` that:
* It requires to re-use `Completion` instance returned from `deferCompletion()` if we want to refer it later, otherwise completion will be leaked
* However we realized that this change could cause a lot of migration cost for Decaton <= 2.x users
- Decaton doc's example code was also outdated
* So we concluded to make keep existing deferCompletion-usage to work by adding fix (https://github.com/line/decaton/pull/124)
* => We should add integration test cases to ensure it works
- Besides, I fixed `ProcessorTestSuite` to await retried-produced tasks to be committed

Add tests for deferred completion

---

brave/build.gradle
build.gradle
centraldogma/build.gradle
docs/example/build.gradle
processor/README.md
processor/build.gradle
protocol/build.gradle
testing/build.gradle

Match dependencies set with the recently upgraded spring-boot version and generally keep the build up-to-date
- Micrometer 1.6.6 -> 1.7.5
- Breaking changes (https://github.com/micrometer-metrics/micrometer/releases/tag/v1.7.0) : support for prometheus-simpleclient < 0.10 is dropped.
- See other release notes for minor changes
- Brave 5.12.6 -> 5.13.3 ( bitter release notes: https://github.com/openzipkin/brave/releases/tag/5.13.2 )
- Centraldogma 0.49 -> 0.52 ( nothing major for our use case : https://github.com/line/centraldogma/releases )

Bump dependencies : micrometer, centraldgoma, brave..

---

build.gradle
docs/example/build.gradle
docs/getting-started.adoc

- Upgrade shadow plugin which has newer log4j2 dependency that is patched for recent RCE vulnerability
* https://github.com/johnrengelman/shadow/releases/tag/7.1.1
- Note that this does **NOT** mean Decaton has log4j2 as the dependency

Upgrade shadow which has newer log4j2 dependency

---

processor/src/it/java/com/linecorp/decaton/processor/CoreFunctionalityTest.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorProperties.java

Related to #37.
Because of the default `decaton.max.pending.records` is conservatively low, Decaton's throughput is not very efficient by default value.
To begin from the conclusion, based on benchmark result, `10_000` seems a suitable property for default value.
**CAUTION : I ran benchmark on my MacBook Pro, so the result may different from real environment.**
```
Environment: MacBook Pro (16-inch, 2019)
Processor: 2.6 GHz 6-Core Intel Core i7
Memory: 16GB
```
I attached 5 benchmark result files.
attached files:
[Benchmark_max_pending_100.txt](https://github.com/line/decaton/files/7684995/Benchmark_max_pending_100.txt)
[Benchmark_max_pending_1000.txt](https://github.com/line/decaton/files/7684996/Benchmark_max_pending_1000.txt)
[Benchmark_max_pending_10000.txt](https://github.com/line/dec …

Increase max.pending.records to 10000

---

protocol/build.gradle

- We added a workaround for Apple M1 in this PR https://github.com/line/decaton/pull/76
- However, I found that it's no longer necessary as already addressed in protobuf-plugin side
* https://github.com/protocolbuffers/protobuf/pull/8557
- Forgot to remove this workaround after the plugin dep was upgraded

After protobuf plugin upgrade, workaround is no longer necessary

---

processor/src/it/java/com/linecorp/decaton/processor/BatchingProcessorTest.java
processor/src/main/java/com/linecorp/decaton/processor/processors/BatchingProcessor.java
processor/src/test/java/com/linecorp/decaton/processor/processors/BatchingProcessorTest.java

- Task batching is a common-pattern that many Decaton users often implement by their own.
- i.e. Batching several tasks of type T to List<T> and process them at once. e.g. when downstream-DB supports batching I/O (which often very efficient)
- Batch-flushing should be done in time-based and size-based.
- So it's better to provide BatchingProcessor built-in to meet the common needs
Related Issue: https://github.com/line/decaton/issues/128

Add batching processor

---

.github/workflows/ci.yml
build.gradle

- Java 17 has already been released, so the usage is expected to be spread in the future
- Add test-target JDK to confirm it works on JDK 17

Test on Java 17

---

build.gradle
processor/build.gradle
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java
testing/build.gradle
testing/src/main/java/com/linecorp/decaton/testing/processor/ProducerAdaptor.java

- Upgrade kafka-clients dependency to the latest version
- But should still work with kafka 2.x
- After https://github.com/apache/kafka/pull/10203, several transitive dependencies that decaton currently depend on are moved from compile-classpath to runtime-classpath (`implementation` gradle config), we need to explicitly add dependencies for them
- Concern:
* Should this change marked as "breaking change" and bump major version?

Upgrade kafka-clients dependency to 3.2.0

---

docs/consuming-any-data.adoc
docs/dynamic-property-configuration.adoc
docs/getting-started.adoc
docs/tracing.adoc
docs/why-decaton.adoc

Some links has been broken before introducing `modules` mechanism.

Fix missing links on docs

---

processor/src/it/java/com/linecorp/decaton/processor/metrics/MetricsTest.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/CompletionImpl.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ProcessPipeline.java

After [this change](https://github.com/line/decaton/pull/99/files#diff-4df160cb6c95ec9c8815d2af1dda8a9ebe841c74c4e094bd3ef8e75074dd0af5L121) in  https://github.com/line/decaton/pull/99, decaton stopped incrementing `taskMetrics.tasksError` for synchronous failure.
This PR wants to fix `tasksError` to work again.
I applied quick patch as first PR, but implementing `completeExceptionally(Throwable)` in [DeferredCompletion](https://github.com/line/decaton/blob/d9543b907cb6af8090b4159eb7cd8fddb4cabac1/processor/src/main/java/com/linecorp/decaton/processor/DeferredCompletion.java) and complete it with exception sounds the right way.
How do you think?

Increment error counter for synchronous failure

---

benchmark/build.gradle
build.gradle
centraldogma/build.gradle
centraldogma/src/main/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplier.java
centraldogma/src/test/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplierIntegrationTest.java
centraldogma/src/test/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplierTest.java
docs/example/build.gradle
processor/build.gradle
testing/build.gradle

Contents
- Bump dependencies for CD, Jackson, SLF4J, Logback
- Fix deprecation warnings related to CD (which recently introduced CentralDogmaRepository)
After this PR, decaton will require CD v0.55+ ( https://github.com/line/centraldogma/releases )

Use centraldogma 0.57

---

build.gradle
processor/src/it/java/com/linecorp/decaton/processor/CoreFunctionalityTest.java
processor/src/it/java/com/linecorp/decaton/processor/SubscriptionStateTest.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/SubscriptionStateListener.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/AssignmentManager.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ConsumeManager.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContexts.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/AssignmentManagerTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ConsumeManagerTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/PartitionContextsTest.java
testing/src/main/java/com/linecorp/decaton/testing/TestUtils.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessorTestSuite.java

- Kafka 2.4 added [cooperative rebalancing](https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol), which aims to minimize well-known "stop-the-world" effect upon consumer rebalance
* Essentially, what cooperative rebalancing achieves is to revoke/assign only necessary partitions on rebalance and allows to fetch on still-owned partitions even during rebalance.
* We can opt-in cooperative rebalancing protocol by specifying `ConsumerConfig.PARTITION_ASSIGNMENT_STRATEGY_CONFIG` property
- However, currently, Decaton doesn't work with cooperative rebalancing for some reasons. This PR gonna fix them
- Deprecated `Consumer#poll(long)` is used
* It's already deprecated and should be replaced with `Consumer#poll(Duration)`
* There are several …

Support cooperative rebalancing fixes #98,#118

---

build.gradle

- My bad, I removed workaround for apple silicon build in https://github.com/line/decaton/pull/148 but forgot to upgrade the plugin, so now still failing on apple silicon

Upgrade protobuf to support apple silicon

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/OffsetState.java

- `OffsetState#timeoutAt` is set by processor threads and reaper thread, while it's read by subscription thread when executing `OOOCC#updateHighWatermark`.
- We should make timeoutAt volatile to ensure latest timeout value is visible from subscription thread

Ensure timeout is visible from subscription thread

---

processor/src/main/java/com/linecorp/decaton/processor/metrics/Metrics.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/DecatonTaskRetryQueueingProcessor.java

In our use cases, we try to detect repeated failures of task processing by logging when tasks are retried.
However, frequent repeated logs tend to be ignored, so we may not notice repeated processing failures for a long time.
Instead, this PR introduces a retry count metric, which can be used for alerting based on thresholds.

Add retry count metric

---

docs/index.adoc

https://github.com/line/decaton/pull/69 added the distributed tracing feature and its document but an index page doesn't have its url. This pull request just adds the url in the index page.

Add missing url on docs

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/RetryConfig.java

Motivation:
To resolve https://github.com/line/decaton/issues/181
Modifications:
- Add `@NonNull` to `backoff`
Result:
- Closes #181
- Users can see NPE before consuming a task

Add NonNull annotation to backoff in RetryConfig

---

client/src/main/java/com/linecorp/decaton/client/DecatonClient.java
client/src/main/java/com/linecorp/decaton/client/internal/DecatonClientImpl.java
client/src/main/java/com/linecorp/decaton/client/internal/DecatonTaskProducer.java
client/src/test/java/com/linecorp/decaton/client/DecatonClientTest.java
client/src/test/java/com/linecorp/decaton/client/internal/DecatonClientImplTest.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/DecatonTaskRetryQueueingProcessor.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/DecatonTaskRetryQueueingProcessorTest.java

Motivation:
To resolve https://github.com/line/decaton/issues/159
Modifications:
- Add a new API to `DecatonClient` and `DecatonTaskProducer`
Result:
- Closes #159
- Users can produce a partition-specified task without redundant code and Inefficient deserialization

Provide a way of specifying a partition when producing a task 

---

processor/src/it/java/com/linecorp/decaton/processor/metrics/MetricsTest.java
processor/src/main/java/com/linecorp/decaton/processor/metrics/Metrics.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContext.java

Motivation:
We can detect `DeferredCompletion ` leak by monitoring `latest consumed offset - last committed offset < max.pending.record`.
Therefore, we need to add these metrics.
Modifications:
- Add the following metrics
- `decaton.offset.last.committed` 
- `decaton.offset.latest.consumed`
Result:
- Closes #39
- Users can monitor `DeferredCompletion` leak

Add metrics to check DeferredCompletion leak

---

centraldogma/src/test/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplierIntegrationTest.java

To fix https://github.com/line/decaton/issues/187, Add retry rule to `CentralDogmaPropertySupplierIntegrationTest`

Add retry rule to CentralDogmaPropertySupplierIntegrationTest to fix flaky test

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorProperties.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionProcessor.java

Motivation:
Described in https://github.com/line/decaton/issues/119
Modifications:
- Add timeout for destroying processors
- Set timeout to `PartitionProcessor#awaitShutdown`
Result:
- Closes #119
- `PartitionProcessor#awaitShutdown` waits up to 1000 ms by default
- Users can easily set this timeout

Introduce a timeout for destroying processors

---

processor/src/it/java/com/linecorp/decaton/processor/PropertyReloadRequestTest.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorProperties.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContexts.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/PartitionContextsTest.java

Motivation:
Described in https://github.com/line/decaton/issues/172
Modifications:
- Reload context per partition when reloading is requested
Result:
- Closes #172 
- Reduces time to resume processing when dynamic property reloaded

Narrow down the scope of waiting for pending tasks to per partition

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java

- As described in the issue, RebalanceInProgressException also could be thrown on commitSync, which should not be treated as fatal

Handle RebalanceInProgressException on sync commit fixes #201

---

centraldogma/src/test/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplierTest.java
processor/src/it/java/com/linecorp/decaton/processor/PropertyReloadRequestTest.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorProperties.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContexts.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/CommitManagerTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ConsumeManagerTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/PartitionContextTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/PartitionContextsTest.java

This PR updates `PartitionContexts` so the `max.pending.records` property can be reloaded at runtime, similar to the `partition.concurrency` property.
Modifications:
- Extract reload listener in `PartitionContexts` and register it for `CONFIG_MAX_PENDING_RECORDS`
- `PartitionContext` now reads the property value from `PartitionScope`
- Cleanup `ProcessorProperties` Javadoc formatting
- Cleanup some `unchecked` code in tests

Make `max.pending.records` property reloadable

---

spring/build.gradle
spring/src/integrationTestSpringBoot2/java/com/linecorp/decaton/spring/test/AutoConfigureDecatonConfigurationTest.java
spring/src/integrationTestSpringBoot2/java/com/linecorp/decaton/spring/test/TestSpringBootApplication.java
spring/src/integrationTestSpringBoot3/java/com/linecorp/decatonl/spring/test/AutoConfigureDecatonConfigurationTest.java
spring/src/integrationTestSpringBoot3/java/com/linecorp/decatonl/spring/test/TestSpringBootApplication.java
spring/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

There has been a change in the auto-configuration file in Spring Boot 3.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files
In the `decaton-spring` module, it is necessary to support both boot 2 and boot 3 until migrating to boot 3.
- In addition to the `spring.factories` used in boot 2, a new configuration file `spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` was added for boot 3 in `META-INF`.
- Integration tests have been created to verify that auto-configuration works in both boot 2 and boot 3.
- If these tests are excessive, I'll remove them.

Support spring boot 3 on decaton-spring

---

centraldogma/src/main/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplier.java
client/src/main/java/com/linecorp/decaton/client/DecatonClient.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/CompletionImpl.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ProcessPipeline.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/Processors.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessPipelineTest.java

- The problem and the cause is described in #211
- Summary of the fixes:
* Considering any user-supplied logic could throw non-RuntimeExceptions when it's implemented by non-Java JVM languages, I changed to catch `Exception` instead of `RuntimeException` where Decaton executes user-supplied logic

Prevent non-RuntimeException causes completion-leak fixes #211

---

.github/workflows/ci.yml
build.gradle

Reverting java 8 support drop by https://github.com/line/decaton/pull/214/commits/ca52c6b1d6e68d3fdd1781a742a57ad64546b7ac as we found there's people still want java8 support.

Bring back java 8 support

---

processor/src/main/java/com/linecorp/decaton/processor/metrics/Metrics.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ProcessPipeline.java

The Decaton client adds timestamps to tasks when they are produced, as well as the scheduled execution time. As mentioned in #208, this allows us to output metrics on the time taken from producing to consuming a task. This can be beneficial for monitoring Decaton processors that require low latency, and for creating alerts.
Additionally, metrics on the delay from the scheduled time are particularly useful in determining whether schedules are being executed in retry topic as expected. If there is a significant delay, Decaton users may realize they need increase throughput somehow.
Resolve #208

Add delivery latency and scheduled delay metrics

---

centraldogma/src/main/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplier.java
centraldogma/src/test/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplierIntegrationTest.java

Cache CD dynamic properties

---

.github/workflows/ci.yml
build.gradle
client/src/test/java/com/linecorp/decaton/client/DecatonClientTest.java
processor/build.gradle
processor/src/it/java/com/linecorp/decaton/processor/VThreadCoreFunctionalityTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessingContextImplTest.java
testing/build.gradle

- Now Decaton compiles only on jdk >= 21 (by https://github.com/line/decaton/pull/224) but since there are many users who still use jdk 8,11,17, we still should run tests on these versions

Ensure decaton works with older jdk

---

benchmark/src/main/java/com/linecorp/decaton/benchmark/Main.java
cb/run-bm.sh

- Now performance dashboard doesn't work because latest run produces invalid JSON output
* https://line.github.io/decaton/commit-data/a3f14197b71c65a7aa8d83b78d5c9756dbf9ca89/tasks_100k_latency_10ms_concurrency_20-benchmark.json
- This is because current version of async-profiler output `Profiling started` on stdout and there seems to be no way to disable this
- To address this, I added `--file` option to the benchmark module to prevent async-profiler output and benchmark output are mixed

Fix invalid json of benchmark output

---

benchmark/debm.sh

Follow up for #224 
It turns out that the throughput degradation after the above PR is by the newly added `-Xcomp` option in debm.sh
https://line.github.io/decaton/

Some fixes for benchmark

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorSubscription.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/SubscriptionBuilder.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/AbstractSubPartitions.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionScope.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/SubscriptionScope.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ThreadPoolSubPartitions.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java

- I noticed that the metrics always use `scope.topic()` after #224.
- I think it's useful to keep metrics separate between normal topic and retry topic. This change will use `scope.topicPartition().topic()` to use the retry topic name for metrics when handling the retry topic.

Use TopicPartition.topic for metrics

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/QuotaApplierImpl.java

- Depending on data, key might contain sensitive information so logging it is not preferable

Fix potential key exposure in PKQ

---

docs/example/build.gradle
docs/example/src/main/java/example/TaskBatchingMain.java
docs/example/src/main/java/example/processors/InsertHelloTask.java
docs/example/src/main/java/example/processors/InsertHelloTaskBatchingProcessor.java
docs/task-batching.adoc

- To add a documentation for `BathingProcessor` like [task-compaction.adoc](https://github.com/line/decaton/blob/master/docs/task-compaction.adoc).
Related Issue: https://github.com/line/decaton/issues/128
Related PR: https://github.com/line/decaton/pull/139

Add task batching doc

---

docs/consuming-any-topic.adoc
docs/dynamic-property-configuration.adoc
docs/example/src/main/java/example/JSONUserEventExtractor.java
docs/example/src/main/java/example/TaskBatchingMain.java
docs/example/src/main/java/example/TaskCompactionMain.java
docs/getting-started.adoc
docs/key-blocking.adoc
docs/monitoring.adoc
docs/rate-limiting.adoc
docs/retry-queueing.adoc
docs/runtime.adoc
docs/task-batching.adoc
docs/task-compaction.adoc
docs/tracing.adoc
docs/why-decaton.adoc

- #238 brings a breaking change, which requires to update docs

Update docs and examples for 9.0.0

---

docs/getting-started.adoc
docs/index.adoc
docs/task-extractor.adoc
processor/src/it/java/com/linecorp/decaton/processor/RetryQueueingTest.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ConsumedRecord.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorProperties.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/ProcessorsBuilder.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/SubscriptionBuilder.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/DecatonTaskRetryQueueingProcessor.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/DefaultTaskExtractor.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ProcessPipeline.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/TaskRequest.java
processor/src/test/java/com/linecorp/decaton/processor/processors/CompactionProcessorTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/ProcessorSubscriptionTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/DecatonTaskRetryQueueingProcessorTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/DefaultTaskExtractorTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessPipelineTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessingContextImplTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessorUnitTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessorsTest.java

- As of Decaton 8.0.1, the most common way to use Decaton was to use DecatonClient as the producer and DecatonProcessor as the consumer, with implementing value Serializer/Deserializer respectively.
- After #238, DecatonClient no longer wraps tasks with `DecatonTaskRequest` protobuf, which means records produced by DecatonClient and ones produced by non-DecatonClient producers (serialized by Kafka's serializer) have identical serialized bytes.
* Then why not making `Deserializer` support consuming non-DecatonClient topics, without forcing users to implement `TaskExtractor` (which is bit bothersome than just a deserializer) ?
- Update documentations and examples
- `ProcessorsBuilder#consuming(String topic, Deserializer<T> deserializer)` now deserializes messages bytes directly even when …

Make Decaton can consume any topic with deserializer

---

processor/src/it/java/com/linecorp/decaton/processor/ProtocolMigrationTest.java
processor/src/it/java/com/linecorp/decaton/processor/RetryQueueingTest.java
testing/src/main/java/com/linecorp/decaton/testing/processor/ProcessorTestSuite.java

- Decaton 9.0.0 contains big breaking change (#238), which needs careful upgrade procedure.
- It's better to check if the procedure works correctly with IT

Add IT to check protocol migration works

---

developer-docs/making-release.md

- user/pass-based authentication is now deprecated on sonatype
- also included common pitfall in PGP signing

Sonatype requires to publish using user token

---

client/src/main/java/com/linecorp/decaton/client/DecatonClientBuilder.java
client/src/main/java/com/linecorp/decaton/client/internal/DecatonClientImpl.java
client/src/test/java/com/linecorp/decaton/client/internal/DecatonClientImplTest.java

Related to: https://github.com/line/decaton/pull/238/files
In https://github.com/line/decaton/pull/238/files and https://github.com/line/decaton/pull/238/files we dropped the DecatonTaskRequest w/ online migration procedure.
However, in the apps that uses both `decaton-processor` and `decaton-client` (i.e, DecatonClient), it is impossible to migrate the app to decaton 9 or above because it inherently upgrades `decaton-client` dep by transitive dep from `decaton-processor` first.
To address this situation I put back the option to let DecatonClient keep producing tasks in older version until all processor completes upgrade. 
After this change the upgrade procedure will be:
* Step1: Upgrade decaton-processors to 9.0.0 or higher with decaton.retry.task.in.legacy.format=true, …

Put back support to produce in the old DecatonTaskRequest for migration

---

client/src/main/java/com/linecorp/decaton/client/internal/TaskMetadataUtil.java
processor/src/it/java/com/linecorp/decaton/processor/ProtocolMigrationTest.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/DecatonTaskRetryQueueingProcessor.java

- As described in #250, current upgrade procedure for CaseD doesn't work because retry tasks might be serialized as old format when `retry.task.in.legacy.format` is true while preserving `dt_meta` if original task is produced by new decaton client
* Existing integration test didn't catch this because the procedure written in release-note and the procedure in integration test wasn't equal... This was the mistake I overlooked.
- Unliked CaseD, current integration test disables `retry.task.in.legacy.format` before upgrading decaton client, which works correctly
- To fix this, we should ensure `dt_meta exists iff the task is in new format` is always true, by removing `dt_meta` when producing retry task in old format
- I formally verified the correctness: …

Fix task parse failure during migration to v9 fixes #250

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/ThreadPoolSubPartitions.java

Fix #252. I apologize if my correction is incorrect.
- As-Is: `decaton.processor.processed.time` measured the time taken to execute [`ThreadPoolExecutor#execute`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/ThreadPoolExecutor.html#execute(java.lang.Runnable)) itself.
- To-Be: This timer measures the time taken to execute `command` (= `processTask(request)`).

Fix `decaton.processor.processed.time` to measure task processing time

---

build.gradle

- OSSRH has reached EoL on June 30th. As a result, we get 403 error when publishing Decaton
* https://central.sonatype.org/news/20250326_ossrh_sunset/
- We have to use new endpoint according to https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/, https://central.sonatype.org/publish/publish-portal-snapshots/#consuming-via-gradle
I confirmed SNAPSHOT version can be released by changing the endpoint. (https://central.sonatype.com/repository/maven-snapshots/com/linecorp/decaton/decaton-common/9.1.1-SNAPSHOT/maven-metadata.xml)
We also need to issue new token on new Poratl and use it, so need to update `developer-docs/making-release.md`. I'll submit follow-up PR after trying to publish in new way.

OSSRH is deprecated

---

centraldogma/build.gradle
centraldogma/src/test/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplierIntegrationTest.java
centraldogma/src/test/java/com/linecorp/decaton/centraldogma/CentralDogmaPropertySupplierTest.java
settings.gradle
spring/build.gradle
spring/src/integrationTestSpringBoot3/java/com/linecorp/decatonl/spring/test/AutoConfigureDecatonConfigurationTest.java

- Found that `centraldogma`'s tests still depend on junit4, while Decaton's global test runner is already migrated to junit5 in #214 
* Due to this, `centraldogma`'s tests were not executed at all unintentionally
- Also, `spring`'s integration tests were not executed because it isn't included in `check` task

Run unintentionally ignored tests

---

processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PartitionContext.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/PerKeyQuotaManager.java
processor/src/main/java/com/linecorp/decaton/processor/runtime/internal/TaskRequest.java
processor/src/test/java/com/linecorp/decaton/processor/processors/CompactionProcessorTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/PartitionContextTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/PerKeyQuotaManagerTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessPipelineTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessingContextImplTest.java
processor/src/test/java/com/linecorp/decaton/processor/runtime/internal/ProcessorUnitTest.java

- Currently, Quota usage is counted twice mistakenly in PartitionContext, which causes keys to reach the quota at the half of quota value and shaped
- Added the test to ensure the double count is fixed.
- Also tested PerKeyQuota feature locally with this code (https://gist.github.com/ocadaruma/4503de325490c2591c0003bcb25540fc#file-realperkeyquotatest-java)
* <img width="1489" height="711" alt="image" src="https://github.com/user-attachments/assets/253179fa-f7e9-4148-b146-8a387a996376" />
* Confirmed worked as expected with quota = 500msg/sec. (400msg/sec -> not shaped, 600msg/sec -> shaped)

PerKeyQuota usage is double counted fixes #265
